### ISSUE TITLE
Add "EXTERNAL_DEBUG_URL" environment variable

### ISSUE THREAD

**Issue by AndrewDryga** [Nebo15/gateway.web#42]
It should contain pattern that will be applied as link (if present) on details tab. Value should have a placeholder that will be replaced by `request_id`.

<img width="503" alt="screen" src="https://cloud.githubusercontent.com/assets/1877644/24521830/1f0ab046-1596-11e7-9e7b-7df9a6c4bcbb.png">

Link should say "Find in external debugger".

**Comment by alexeybondarenko** [comment]
As I've understood @AndrewDryga we need to add a new link Open in Debugger next to Copy CURL. A debugger is an external system. A link on debugger could be is specifying in `EXTERNAL_DEBUG_URL`. eg. https://example.com/{request_id}/logs. UI need to replace {request_id} with `request_id` of request.
